# Generated by Django 4.2.10 on 2024-07-28 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('category', models.CharField(max_length=100, verbose_name='カテゴリ')),
                ('status', models.CharField(max_length=100, verbose_name='状態')),
                ('location', models.CharField(max_length=100, verbose_name='設置場所')),
                ('description', models.TextField(verbose_name='説明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_images/', verbose_name='画像')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='在庫数')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
