# Generated by Django 4.2.10 on 2024-07-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_orderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
