# Generated by Django 4.2.10 on 2024-07-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_orderrequest_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='note',
        ),
    ]
